AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template EC2_Instancetance in an existing VPC.
Parameters:
  VpcId:
    Type: String
    Default: vpc-fced2c84
    Description: VpcId of your existing Virtual Private Cloud (VPC)
  SubnetId:
    Type: String
    Default: subnet-00f953beb0966e343
    Description: SubnetId of an existing subnet in your Virtual Private Cloud (VPC)
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-03e05c89aa11dda83
      NetworkInterfaces:
        - DeviceIndex: '0'
          AssociatePublicIpAddress: 'true'
          DeleteOnTermination: 'true'
          SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: test-tm-demo-swapnil
      UserData: !Base64 
        'Fn::Sub': |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          chkconfig httpd on
          service httpd start
          echo "Success!!!" > /var/www/html/index.html
          curl -O https://downloads.apache.org/tomcat/tomcat-8/v8.5.57/bin/apache-tomcat-8.5.57.tar.gz
          tar xvfz apache*.tar.gz
          mv apache-tomcat-8.5.57/* /opt/tomcat/.
          apt install java
          java -version
Outputs:
  InstanceId:
    Value: !Ref Ec2Instance
    Description: Instance Id of newly created instance
