AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation Template EC2_Instancetance in an existing VPC.
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0ebc1ac48dfd14136
      NetworkInterfaces:
        - DeviceIndex: '0'
          AssociatePublicIpAddress: 'true'
          DeleteOnTermination: 'true'
      Tags:
        - Key: Name
          Value: test-instance-demo
      UserData: !Base64 
        'Fn::Sub': |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          chkconfig httpd on
          service httpd start
          echo "Success!!!" > /var/www/html/index.html
Outputs:
  InstanceId:
    Value: !Ref Ec2Instance
    Description: Instance Id of newly created instance
